from enum import Enum


class JobStatus(str, Enum):
    UPLOADED = "UPLOADED"

    EXTRACTING_AUDIO = "EXTRACTING_AUDIO"

    DETECTING_SPEECH = "DETECTING_SPEECH"

    TRANSCRIBING = "TRANSCRIBING"

    MERGING = "MERGING"

    GENERATING_PDF = "GENERATING_PDF"

    COMPLETED = "COMPLETED"

    FAILED = "FAILED"